sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.11.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - docker-compose -f docker/docker-compose.yml pull
  - docker-compose -f docker/docker-compose.yml up -d
  - docker ps

script:
  - docker-compose -f docker/docker-compose.yml run truffle3_ens /bin/sh -c "npm install"
  - docker-compose -f docker/docker-compose.yml run truffle3_ens /bin/sh -c "/root/truffle/cli.js compile"
  - docker-compose -f docker/docker-compose.yml run truffle3_ens /bin/sh -c "/root/truffle/cli.js migrate"
  - docker-compose -f docker/docker-compose.yml run truffle3_ens /bin/sh -c "/root/truffle/cli.js test"

  # if you want to migrate and test on a different network, here's the command you'd run
  #- docker-compose -f docker/docker-compose.yml run truffle3 /bin/sh -c "/root/truffle/cli.js test --network ropsten"
  #- docker-compose -f docker/docker-compose.yml run truffle3 /bin/sh -c "/root/truffle/cli.js migrate --network ropsten"
