sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.9.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - docker-compose -f docker/docker-compose.yml pull
  - docker-compose -f docker/docker-compose.yml up -d
  - docker ps

script:
  - docker-compose -f docker/docker-compose.yml run truffle3 /bin/sh -c "npm install; /root/truffle/cli.js compile; /root/truffle/cli.js migrate; /root/truffle/cli.js test"
  - docker-compose -f docker/docker-compose.yml run truffle3 /bin/sh -c "/root/truffle/cli.js migrate --network staging"
  - docker-compose -f docker/docker-compose.yml run truffle3 /bin/sh -c "/root/truffle/cli.js migrate --network ropsten"
